### ISSUE TITLE
باگ کارنکردن وارپ

### ISSUE THREAD

**Issue by dvltak** [hiddify/Hiddify-Server#3278]
سلام وقتتون بخیر 
وارپ بعد از ریلز نسخه ۸ یهو از کار افتاد 
داخل وضعیت اکتیو زده کلید و ایپی وارپ و عوض کردم ریبیلد و دوباره تست کردم فایروالم خاموش کردم مشکل حل نشد 
سرور جدید گرفتم تیک وارپ و زدم باز مشکل حل نشد هنو کار نمیکرد
(وارپ بقیه پنلارو رو سرور جدید تست کردم بدون مشکل کار میکرد)
ابونتو ۲۰
دیتاسنتر هتزنر المان و فنلاند

**Comment by Eslender73** [comment]
خیلی ممنون از گزارشتون
دولوپر های عزیزمون در جریان این مشکل هستن در حال عیب یابی و ارائه نسخه بدون ایراد هستن
بزودی مشکل برطرف خواهد شد

**Comment by alinasiri8102** [comment]
hello.
warp on my vps has some issue too, i'm giving you my outputs so it may be helpful.

on status page wg-quick@warp is failed.

when i try to "change ip" i get this:
https://raw.githubusercontent.com/fscarmen/warp/main/api.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.110.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-10-07 18:26:06 ERROR 404: Not Found.

(it seems repository changed to "https://gitlab.com/fscarmen/warp")

and at the end it gives me this:
Job for wg-quick@warp.service failed because the control process exited with error code.
See "systemctl status wg-quick@warp.service" and "journalctl -xeu wg-quick@warp.service" for details.
Job for wg-quick@warp.service failed because the control process exited with error code.
See "systemctl status wg-quick@warp.service" and "journalctl -xeu wg-quick@warp.service" for details.

and this is the result of "systemctl status wg-quick@warp.service"
Oct 07 18:30:13 213.142.157.147 systemd[1]: Starting WireGuard via wg-quick(8) for warp...
Oct 07 18:30:13 213.142.157.147 wg-quick[2230006]: [#] ip link add warp type wireguard
Oct 07 18:30:13 213.142.157.147 wg-quick[2230013]: RTNETLINK answers: Operation not supported
Oct 07 18:30:13 213.142.157.147 wg-quick[2230006]: [#] ip link delete dev warp
Oct 07 18:30:13 213.142.157.147 wg-quick[2230014]: Cannot find device "warp"
Oct 07 18:30:13 213.142.157.147 systemd[1]: wg-quick@warp.service: Main process exited, code=exited, status=1/FAILURE
Oct 07 18:30:13 213.142.157.147 systemd[1]: wg-quick@warp.service: Failed with result 'exit-code'.
Oct 07 18:30:13 213.142.157.147 systemd[1]: Failed to start WireGuard via wg-quick(8) for warp.

i'm on ubuntu 22.04 and i have tested on 20.04 as well, but same result.

i don't know but maybe its a data center issue.
i hope this helps.
thanks a lot.

**Comment by amin2plus** [comment]
سلام ، با تشکر از زحمات فراوان، 
همچنان این مشکل توی نسخه 8.6.6 وجود داره ، دیروز یک سرور نو بالا آوردم و وارپ کار نمیکنه، 
میخواستم یک issue جدید باز کنم ولی گفتم اول issue قدیمی هارو چک کنم تا شاید راه حل ای پیدا بشه ، 
لطف میکنید اگر مشکلاتی که برطرف نشده رو close نکنید تا برای اونها که issue قدیمی ها رو چک نمیکنند doublicate کاری نشه 
و حتی ممکنه یکی یک کامنتی بگذاره که برای برطرف کردن مشکل مفید باشه

**Comment by amin2plus** [comment]
> سلام ، با تشکر از زحمات فراوان، همچنان این مشکل توی نسخه 8.6.6 وجود داره ، دیروز یک سرور نو بالا آوردم و وارپ کار نمیکنه، میخواستم یک issue جدید باز کنم ولی گفتم اول issue قدیمی هارو چک کنم تا شاید راه حل ای پیدا بشه ، لطف میکنید اگر مشکلاتی که برطرف نشده رو close نکنید تا برای اونها که issue قدیمی ها رو چک نمیکنند doublicate کاری نشه و حتی ممکنه یکی یک کامنتی بگذاره که برای برطرف کردن مشکل مفید باشه

خواستم بگم با رفتن به پنل بتا (که ارور میده و نصب نمیشه) و برگشتن به پنل استیبل، مشکل وارپ برطرف مشه (شاید کمک کنه)
